# Generated by Django 6.0.3 on 2026-03-26 07:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=16)),
                ('metric_1', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metric_2', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('metric_3', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2026, 3, 26, 7, 26, 50, 804229, tzinfo=datetime.timezone.utc))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
