# Generated by Django 6.0.3 on 2026-03-26 13:07
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_initial_user(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')

    CustomUser.objects.create(
        user_id='U0001',
        username='admin',
        name='Admin User',
        password=make_password('password'),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_iotdata'),
    ]

    operations = [
        migrations.RunPython(create_initial_user),
    ]
